### ISSUE TITLE
Systemd service environment override problems

### ISSUE THREAD

**Issue by canercidam** [forta-network/forta-node#544]
- There are complaints that overriding from `/etc/systemd/system/forta.service.d/env.conf` does not work on all systems. We need to verify the failure cases in the most commonly used operating systems and make better suggestions in the docs: https://docs.forta.network/en/latest/scanner-quickstart/#configure-systemd
  - Ubuntu
  - Debian
  - CentOS
  - Fedora
- Some people seem to have preferred modifying `forta.service` directly since it was the only way they were able to make `forta` work by using `systemd`. Next time they update the CLI, `forta.service` will be overwritten and the secrets will be gone. To remedy this, YUM and APT packaging should back up `forta.service` as `forta.service.bak` first.

**Comment by aomerk** [comment]
I doubt a systemd problem would be distro dependent, feels more like a layer 8 problem. We might need more info to reproduce the error.
***
Possible steps to reproduce (could not reproduce):

```bash
$ echo "[Unit]
Description=env var mock systemd service unit file.

[Service]
ExecStart=/bin/bash -c \"echo \$FORTA_TEST_ENV\"

[Install]
WantedBy=multi-user.target" > /usr/lib/systemd/system/mocksys.service

$ mkdir -p /etc/systemd/system/mocksys.service.d
$ echo "[Service]
Environment=\"FORTA_TEST_ENV=test123\"" > /etc/systemd/system/mocksys.service.d/env.conf

$ systemctl daemon-reload
$ systemctl start mocksys
$ journalctl -u mocksys
```

- [X] CentOS
- [X] Fedora
- [X] Ubuntu
- [X] Debian
