### ISSUE TITLE
`trace_block` failures cause generating different alert IDs

### ISSUE THREAD

**Issue by canercidam** [forta-network/forta-node#546]
Among five nodes, three of them failed to fetch block trace data from the same source. One of the node logged the error as:
```json
{
   "blockHash":"0x4bcf1619e39b5b21ae39b682e6b188519871c4c217a840c0290dc6509269c543",
   "blockToAnalyze":15211626,
   "blockToAnalyzeHex":"0xe81c6a",
   "currentBlock":15211626,
   "error":"503 Service Unavailable: {\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32000,\"message\":\"Unable to complete request at this time.\"},\"id\":30675}",
   "level":"error",
   "msg":"error tracing block",
   "time":"2022-07-25T12:22:27Z"
}
```
This error is logged when all retries finally fail: https://github.com/forta-network/forta-core-go/blob/731a8e17df53d30f2473a0579a41ba02491a5aac/feeds/blocks.go#L229

Alert 1: https://explorer.forta.network/alert/0x2e6da2e2b64f7fc3f0f8b2249a2d110ad18398a048ce486c31ff718464f6ffd2
Alert 2: https://explorer.forta.network/alert/0x16d0d4cae4055bcd419840264c7027cb66830b841bf960fed7701293c9456324

Batch for alert 1: https://alerts.forta.network/batch/QmUkCnztsps1ZuBcN4nPNEBEfWu2JQwjd9MHo9gVHHne5e/decoded
Batch for alert 2: https://alerts.forta.network/batch/QmegLASixBt7QEk1ctWA4Zg96NqdepE47yisP3w27gN5sr/decoded

Batch 1 doesn't have the block trace data among the inputs of alert 1, but batch 2 has it for alert 2. This created a difference of 9 addresses in the output and caused the alert hash to be calculated differently.

As a solution, we could exclude trace addresses from `addresses`, put them to `traceAddresses` and use only `addresses` in hash calculation. This could be useful in the future if we try to unify the alerts from nodes which do and don't require tracing while scanning the same chain.

**Comment by aomerk** [comment]
I feel like we should stop feeding data to bots if the tracing is enabled and node has failed to fetch trace data. 

Excluding trace data is a solution for this specific problem, but not `continue`'ing [here](https://github.com/forta-network/forta-core-go/blob/731a8e17df53d30f2473a0579a41ba02491a5aac/feeds/blocks.go#L229) adds inconsistency to trace-using bot outputs

**Comment by canercidam** [comment]
That's another solution. But if it's only the trace that's failing and the error is persistent for a long time, should we fail the whole scan operation? Or let the majority of the bots keep on doing their work and fire useful alerts? If we blocked the flow, 3 out of 5 scanners mentioned in the description would have fired no alerts at all due to the error being persistent.

**Comment by aomerk** [comment]
For the most of the time (assuming minority of bots are using trace data), ignoring trace error increases the overall uptime(?) of the network. 

However, I still think that data inconsistency is a concern. Either between the results of 2 different scan nodes, or when we re-run the bot against the same block range. 

I think this discussion has a lot of correlation with how much trace support should effect SLA. fwiw, the scan node should've provided trace data (if required), and failed to do so. Doesn't really matter if all assigned bots use trace data or none does. 

Question: Does removing trace addresses from the alert hash have a downside that we can think of? We could just remove trace addresses if they don't have a valuable contribution to the hash and continue discussing the execution side of this problem

**Comment by canercidam** [comment]
> Does removing trace addresses from the alert hash have a downside that we can think of?

There isn't because the addresses from trace are just details. They are the addresses that were involved during EVM execution so they are important but using the addresses from the transaction should be sufficient enough to make the alert unique.

I'm afraid of stopping the flow of alerts regardless of the node performance. Even though these alerts were different and the scan nodes partly failed at the scanning work, it makes more sense to reflect this to how the scan node is rewarded and not punish the consumer.
